### ISSUE TITLE
Provide pure-floss build flavor

### ISSUE THREAD

**Issue by ghost** [imshyam/mintube#1]
This app uses non-free crashlytics. Could you provide a gradle build flavor that does not require this or use free alternatives like acra for it?

**Comment by imshyam** [comment]
Crashlytics is also free now. [Here](http://try.crashlytics.com/pricing/) is the proof.

**Comment by ghost** [comment]
I was not talking about pricing, but about free as in freedom. I couldnt find the sourcecode to crashlytics und a free/libre/opensource license, maybe you could point me to that?
