### ISSUE TITLE
Crashlytics && fabrics.io seem problematic

### ISSUE THREAD

**Issue by nine7nine** [imshyam/mintube#10]
Hey,

I really like your app, however, is there anyway you could get rid of (or switch) from using Crashlytics and fabric.io??

I can't even build this app anymore due to fabrics.io requiring an account and even when I signed up for one, they never sent my confirmation email (tried several times)... I know that Crashlytics was also a blocker in getting your app into F-Droid repo...

Idk, I think Crashlytics & fabrics.io are very inconvenient to be using. Anyway, at least I still have more older builds, but it would have been nice to try and hack on the app a little.

These problems aside, great app, great idea!

**Comment by ghost** [comment]
Commit 44e31049b426819a0c844598f824d806e4157d37 fixes this.
