### ISSUE TITLE
App crashes/disappears 

### ISSUE THREAD

**Issue by ClausMunch** [imshyam/mintube#15]
Hi,

I recently got the OnePlus 3T (Android 7.1.1) and mintube crashes/disappears when trying to start a video.. Any idea on why?

Brg

**Comment by knezi** [comment]
This: https://github.com/imshyam/mintube/commit/8dfb784bd5392e70ffbd5610cc68c2f74e32ae4c solves it. You can wait for next release or build the master on your own. Alternatively, you can download my unsigned build at http://www.ms.mff.cuni.cz/~knizekj1/ap-debug.apk. Use at your own risk.
SHA256SUM: b981949b373401f34d0456bd735cbb7ea59017e849315a7593ae7ebbe9b3887f

**Comment by imshyam** [comment]
Also, the signed APK that fixed this bug is available at [bit.ly/mintube](http://bit.ly/mintube).
