### ISSUE TITLE
Lower SDK

### ISSUE THREAD

**Issue by Fiks33** [imshyam/mintube#2]
Can this App work with lower SDK to API 14 ?

**Comment by imshyam** [comment]
Hi,

Right now minimum support API level is 21. The functionality of the app is like facebook-massenger's chat heads. So if the chat heads can be implemented for API 14, then this app will also work for that.

By the way I'm working on that and will let you know once it's done.

Thanks for showing the interest.

**Comment by Fiks33** [comment]
Ok thanks Btw thats a good project for release in playstore
