### ISSUE TITLE
Force Close 

### ISSUE THREAD

**Issue by methuselahin** [imshyam/mintube#22]
The application force of some ROMs of 7.1.1 whenever i try to open video with the app. I have given the required permissions too. But still the issue persists. I am attaching log for the same. My phone is KIWI( Honor 5x) [https://pastebin.com/V8cUAY8p](url)

**Comment by methuselahin** [comment]
@imshyam

**Comment by imshyam** [comment]
Hi,

Will fix as I get some time. Meanwhile feel free to contribute.

**Comment by methuselahin** [comment]
@imshyam I don't have programming knowledge. But I know how to grab log so reported. I suppose you doing this as project.. Glad to see Indians joining git too....
