### ISSUE TITLE
How could I play a list?

### ISSUE THREAD

**Issue by oososo** [imshyam/mintube#24]
How could I play a list ? I add a list in it , but it only play first song , it couldn't turn to next. Thanks so much for help.

**Comment by imshyam** [comment]
Hi, The feature is working. You can simply click on the next button inside the player or in the notification. Using the notification you can go to the previous song too. Check the other features [here](http://imshyam.github.io/mintube/). Also, find the attached images below for playing next song.
![screenshot_1495036449](https://cloud.githubusercontent.com/assets/3381173/26163423/479f58f4-3b5c-11e7-8eb5-d3539505fcbe.png)
![screenshot_1495036473](https://cloud.githubusercontent.com/assets/3381173/26163427/4abe2ed4-3b5c-11e7-9d79-7e988b2b93ff.png)
