### ISSUE TITLE
App refuses to play any selected video. It reloads instead.

### ISSUE THREAD

**Issue by liobash** [imshyam/mintube#39]
#### Expected behavior
Videos are expected to play as soon as they are been clicked on

#### Actual behavior
Instead, another list of videos appears without playing the clicked video

#### How to reproduce
To reproduce this, follow the steps below
1. Launch the application,
2. Allow the videos to load then click on any of the videos to play,
3. While waiting for the clicked video to play, another set of videos are displayed
4. Go back to step 2. This will keep happening non stop.

* Browser/App version: Application version is 0.97
* Operating system: tecno K8 version 7.0

#### Recording Of The Bug
https://youtu.be/7xuKh19In9o

**Comment by imshyam** [comment]
It's fixed now. Please try now.
