### ISSUE TITLE
Black screen with grey play symbol just before video plays. Samsung S5 and S7 (Sprint)

### ISSUE THREAD

**Issue by wrightpt** [imshyam/mintube#6]
Do you know why this occurs?

**Comment by wrightpt** [comment]
Can submit screen shot if prefer.

**Comment by imshyam** [comment]
Yes, That's because I'm using YouTube's ifame APIs. That's not any bug or feature.

**Comment by wrightpt** [comment]
no ads ever play it seems. i think there is a work around but it doesnt
involve using webview. do u know of any?
